<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '机器人本体',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => '3',
    'level' => 0,
    'id' => '1',
    'name' => '机器人本体',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'KR5 Arc',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '5',
    'name' => 'KR5 Arc',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'KR5 R1400',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => 'KR5 R1400',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'KR16',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => 'KR16',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'KR210',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => 'KR210',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '机器人变位机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '机器人变位机',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '连动',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => '连动',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '非连动',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '7',
    'name' => '非连动',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '焊接机器人',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '焊接机器人',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => 'KR5 Arc系统',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => 'KR5 Arc系统',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => 'KR5 R1400弧焊包',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => 'KR5 R1400弧焊包',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '切割机器人',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => '3',
    'level' => 0,
    'id' => '16',
    'name' => '切割机器人',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'KR16智能火焰切割包',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => 'KR16智能火焰切割包',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => 'KR5 Arc智能等离子切割包',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => 'KR5 Arc智能等离子切割包',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'KR5 R1400火焰切割包',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => 'KR5 R1400火焰切割包',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'KR5 Arc智能火焰切割包',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => 'KR5 Arc智能火焰切割包',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'KR16智能等离子切割包',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => 'KR16智能等离子切割包',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'KR5 R1400等离子切割包',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => 'KR5 R1400等离子切割包',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '雕刻机器人',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '雕刻机器人',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'KR210智能雕刻包',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => 'KR210智能雕刻包',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => 'KR5 R1400基础雕刻包',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => 'KR5 R1400基础雕刻包',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => 'KR5 Arc智能雕刻包',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => 'KR5 Arc智能雕刻包',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '机器人配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '3',
    'goods_num' => '3',
    'level' => 0,
    'id' => '33',
    'name' => '机器人配件',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '本体',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '本体',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '软件',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '软件',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '电器',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '电器',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '示教器',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '46',
    'name' => '示教器',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '线缆',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '45',
    'name' => '线缆',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '控制柜',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '44',
    'name' => '控制柜',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '其它配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '40',
    'name' => '其它配件',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '切割',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '切割',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '切割枪',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '51',
    'name' => '切割枪',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '焊接',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '焊接',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '焊接电源',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '49',
    'name' => '焊接电源',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '焊枪',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '50',
    'name' => '焊枪',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '雕刻',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '雕刻',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '夹持器',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '54',
    'name' => '夹持器',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '动力头',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '52',
    'name' => '动力头',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '换枪位置',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '53',
    'name' => '换枪位置',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '其它',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '其它',
  ),
);
?>